version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - ./data:/data/import:ro
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:1.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  jupyter:
    build: ./jupyter
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  data-loader:
    image: mongo:6.0
    command: >
      bash -c "sleep 5 &&
               mongoimport --host mongo --db german_credit --collection records --type csv --headerline --file /data/import/german_credit.csv --drop"
    volumes:
      - ./data:/data/import:ro
    depends_on:
      - mongo
    restart: "no"

volumes:
  mongo_data:


